# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_album_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='template',
            field=models.CharField(default='templates/search.html', max_length=200),
        ),
    ]
