# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_album_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='template',
        ),
        migrations.AddField(
            model_name='album',
            name='path',
            field=models.CharField(default='templates/search', max_length=200),
        ),
    ]
