# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0006_remove_album_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='path',
            field=models.CharField(default='templates/search', max_length=200),
        ),
    ]
