# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0007_album_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('numProducts', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.CharField(default='PinkFloyd.jpeg', max_length=200),
        ),
    ]
